### ISSUE TITLE
Introduce configuration file

### ISSUE THREAD

**Issue by arnolanglade** [nidup/architool#5]
* **a step** represent a group of actions
* **an action** represent a `Command` you want to handle, we need to specify its class and those arguments.
 
```yml
steps:
    move_akeneo_bundle_component:
        - name: move_folder
          arguments:
            - 'Akeneo/Component'
            - 'Akeneo/Common/Component'
        - name: move_folder
          arguments:
            - 'Akeneo/Component'
            - 'Akeneo/Common/Component'
    create_product_enrichment:
        - name: move_folder
          arguments:
            - 'Pim/Component/Catalog'
            - 'Akeneo/Pim/ProductEnrichment/Domain'
        - name: move_folder
          arguments:
            - 'Pim/Component/Catalog'
            - 'Akeneo/Pim/ProductEnrichment/Domain'
```

**TODO:**

- [ ] Rework `HexagonalizeCommand`, it should be able to read the configuration file to create command and sent them to the bus.
- [ ] Remove `Nidup\Architool\Application\Project`

**Comment by arnolanglade** [comment]
# Version 2:

* **a step** represent a group of actions
* **an action** represent an action to do on your code base. For instance 'move a class'
 


### Project migration configuration

```yml
steps:
    move_akeneo_bundle_component:
        - name: move_legacy_folder
          arguments:
            - 'Akeneo/Component'
            - 'Akeneo/Common/Component'
        - name: move_legacy_folder
          arguments:
            - 'Akeneo/Component'
            - 'Akeneo/Common/Component'
    create_product_enrichment:
        - name: move_legacy_folder
          arguments:
            - 'Pim/Component/Catalog'
            - 'Akeneo/Pim/ProductEnrichment/Domain'
        - name: reconfigure_spec_folder
          arguments:
            - 'Pim/Component/Catalog'
            - 'Akeneo/Pim/ProductEnrichment/Domain'
```

**TODO:**
- [ ] Define the domain `Project`, `Step` ?
- [ ] Rework `HexagonalizeCommand`, it should be able to read the configuration file to create command.
- [ ] Remove `Nidup\Architool\Application\Project`
